name: Build

on:
    push:
        branches:
        - 1.**.**
    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Java
          uses: actions/setup-java@v3
          with:
              distribution: temurin
              java-version: 17

        - name: Cache
          uses: actions/cache@v2
          with:
              path: |
                  ~/.gradle/caches
                  ~/.gradle/loom-cache
                  ~/.gradle/wrapper
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
              restore-keys: ${{ runner.os }}-gradle

        - name: Build
          run: ./gradlew build

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: Renewables
              path: build/libs/

        - name: Send webhook notification
          if: always()
          run: |
              git clone https://github.com/encode42/discord-workflows-webhook.git webhook
              bash webhook/send.sh ${{ job.status }} ${{ secrets.WEBHOOK_URL }}
          shell: bash